-- create schema for testing series data
CREATE SCHEMA SERIES_DATA;

-- creating a series table

CREATE COLUMN TABLE SERIES_DATA.MACHINE_READINGS (
	SENSOR VARCHAR(15), 
	TIMER TIMESTAMP, 
	READING DECIMAL(10,2)
)
SERIES (
	SERIES KEY(SENSOR) 
	PERIOD FOR SERIES(TIMER)
	EQUIDISTANT INCREMENT BY INTERVAL 1 HOUR
	MINVALUE '2015-01-01 00:00:00'
	MAXVALUE '2015-12-31 23:00:00'
 );
 
-- inserting manufactured data into the new series table

DELETE FROM SERIES_DATA.MACHINE_READINGS;
INSERT INTO SERIES_DATA.MACHINE_READINGS (
	-- the following is manufactured / fake data
	SELECT 
		'MACHINE_1', 
		GENERATED_PERIOD_START, 
		ROUND(20+RAND()*20,1) 
	FROM 
		SERIES_GENERATE_TIMESTAMP('INTERVAL 1 HOUR', '2015-01-01', '2015-11-01')
);

SELECT * FROM SERIES_DATA.MACHINE_READINGS
ORDER BY TIMER DESC;

 -- look at the underlying series which has been created

SELECT *
FROM SERIES_GENERATE_TIMESTAMP (
 	SERIES TABLE SERIES_DATA.MACHINE_READINGS
);

SELECT 
	SERIES_PERIOD_TO_ELEMENT(
    	'2015-10-31 19:00' ,
    	SERIES TABLE SERIES_DATA.MACHINE_READINGS
	) AS ELEMENT_20151031_1900,
	SERIES_ELEMENT_TO_PERIOD(
    	500,
    	SERIES TABLE SERIES_DATA.MACHINE_READINGS
	) AS PERIOD_500
FROM DUMMY;
